---
title: "codebook"
author: "edida"
date: "23 July 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

**The run_analysis.R script performs the data preparation and then followed by the 5 steps required as described in the course project’s definition.**

**Download the dataset**
Dataset downloaded using the download.file(), unziped using unzip() the data extracted and the list of files in the folder viewed through the list.files()

**Read the data into R using read.table()**
Fea_testx_data <- read.table(file.path(path_rf, "test" , "x_test.txt" ),header = FALSE)
Fea_trainx_data <- read.table(file.path(path_rf, "train", "x_train.txt"), header =FALSE)
Act_testy_data <- read.table(file.path(path_rf, "test", "y_test.txt"), header = FALSE)
Act_trainy_data <- read.table(file.path(path_rf, "train", "y_train.txt"), header = FALSE)
subjectdata <- read.table(file.path(path_rf,"test", "subject_test.txt"), header = FALSE)
subject_train <- read.table(file.path(path_rf, "train", "subject_train.txt"), header = FALSE)

**merge the train and test data into one** 
#concate by rows
dataSubject <- rbind(subject_train, subjectdata)
dataActivity<- rbind(Act_testy_data, Act_trainy_data)
dataFeatures<- rbind(Fea_testx_data, Fea_trainx_data)
#set variables to names
names(dataSubject)<-c("subject")
names(dataActivity)<- c("activity")
dataFeaturesNames <- read.table(file.path(path_rf, "features.txt"),head=FALSE)
names(dataFeatures)<- dataFeaturesNames$V2
#merge by columns
Combinedata <- cbind(dataSubject, dataActivity)
Merged <- cbind(dataFeatures, Combinedata)
**extracts only measurements on mean and s.d for each measurement**
#subset
subdataFeaturesNames<-dataFeaturesNames$V2[grep("mean\\(\\)|std\\(\\)", dataFeaturesNames$V2)]
selectedNames<-c(as.character(subdataFeaturesNames), "subject", "activity" )
Data<-subset(Merged,select=selectedNames)
**Uses descriptive activity names to name the activities in the data set**
activityLabels <- read.table(file.path(path_rf, "activity_labels.txt"),header = FALSE)
head(Data$activity,30)
**Appropriately labels the data set with descriptive variable names**
names(Data)<-gsub("^t", "time", names(Data))
names(Data)<-gsub("^f", "frequency", names(Data))
names(Data)<-gsub("Acc", "Accelerometer", names(Data))
names(Data)<-gsub("Gyro", "Gyroscope", names(Data))
names(Data)<-gsub("Mag", "Magnitude", names(Data))
names(Data)<-gsub("BodyBody", "Body", names(Data))
names(Data)
**Creates a second,independent tidy data set and ouput**
Data2<-aggregate(. ~subject + activity, Data, mean)
Data2<-Data2[order(Data2$subject,Data2$activity),]
write.table(Data2, file = "tidydata.txt",row.name=FALSE)
**produce rmarkdown codebook**
library(knitr)
knit2html("codebook.Rmd");












